const fs=require('fs');
let c=fs.readFileSync('src/pages/Services.tsx','utf8');

const newData = \const servicesData: AwsServiceInfo[] = [
  { id: 'ec2', name: 'Amazon EC2', category: 'Computación', desc: 'Capacidad de cómputo segura y redimensionable en la nube. Permite lanzar servidores virtuales bajo demanda.', func: 'Servidores Virtuales', status: 'Activo', icon: Server, color: 'text-orange-600', bg: 'bg-orange-100', details: { region: 'us-east-1', tier: 'T3.Micro', uptime: '99.99%', lastUpdated: 'Hoy, 08:30 AM', price: '0.0416/h', latency: '45ms' } },
  { id: 's3', name: 'Amazon S3', category: 'Almacenamiento', desc: 'Almacenamiento de objetos construido para almacenar y recuperar cualquier cantidad de datos desde cualquier lugar.', func: 'Almacenamiento de Archivos', status: 'Activo', icon: HardDrive, color: 'text-green-600', bg: 'bg-green-100', details: { region: 'Global', tier: 'S3 Standard', uptime: '99.9999%', lastUpdated: 'Hace 2 días', price: '0.023/GB', latency: '120ms' } },
  { id: 'rds', name: 'Amazon RDS', category: 'Base de Datos', desc: 'Servicio de base de datos relacional administrado. Facilita la configuración y escalabilidad de bases de datos.', func: 'Base de Datos Relacional', status: 'En Mantenimiento', icon: Database, color: 'text-blue-600', bg: 'bg-blue-100', details: { region: 'us-east-1', tier: 'db.t3.small', uptime: '98.50%', lastUpdated: 'Hace 1 hora', price: '0.068/h', latency: '15ms' } },
  { id: 'iam', name: 'AWS IAM', category: 'Seguridad', desc: 'Administre el acceso a los servicios y recursos de AWS de manera segura mediante políticas granulares.', func: 'Gestión de Accesos', status: 'Activo', icon: Users, color: 'text-red-600', bg: 'bg-red-100', details: { region: 'Global', tier: 'Gratuito', uptime: '100%', lastUpdated: 'Hace 1 semana', price: 'Gratis', latency: '<10ms' } },
  { id: 'vpc', name: 'Amazon VPC', category: 'Redes', desc: 'Aísle lógicamente sus recursos en una red virtual definida y controle todo el tráfico de red.', func: 'Red Privada Virtual', status: 'Activo', icon: Shield, color: 'text-emerald-600', bg: 'bg-emerald-100', details: { region: 'us-east-1', tier: 'VPC con NAT Gateway', uptime: '100%', lastUpdated: 'Ayer', price: '0.045/h', latency: '<5ms' } },
  { id: 'route53', name: 'Amazon Route 53', category: 'Redes', desc: 'Servicio web de DNS en la nube, altamente disponible y escalable para enrutar el tráfico de usuarios.', func: 'Resolución DNS', status: 'Activo', icon: Waypoints, color: 'text-orange-500', bg: 'bg-orange-50', details: { region: 'Global', tier: 'Zonas Alojadas', uptime: '100%', lastUpdated: 'Hace 1 mes', price: '0.50/zona', latency: 'Global' } },
  { id: 'cloudfront', name: 'Amazon CloudFront', category: 'Redes', desc: 'Red de entrega de contenido (CDN) rápida, altamente segura y programable para datos estáticos y dinámicos.', func: 'CDN Global', status: 'Optimizado', icon: Cloud, color: 'text-purple-600', bg: 'bg-purple-100', details: { region: 'Global', tier: 'Optimización Cache', uptime: '99.99%', lastUpdated: 'Hoy, 10:15 AM', price: '0.085/GB', latency: '20ms' } },
];\

c = c.replace(/const servicesData: AwsServiceInfo\[\] = \[[\s\S]*?\];/, newData);
fs.writeFileSync('src/pages/Services.tsx', c, 'utf8');
